env:
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: 0,
  import/extensions: 0,
  indent: [error, 2],
  no-unused-vars: 0,
  consistent-return: 0,
  max-len: 0
}
